# Generated by Django 3.2.4 on 2021-08-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store_app.book'),
            preserve_default=False,
        ),
    ]
