# Generated by Django 3.2.4 on 2021-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_orderdetail_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'User cart'), ('fixed', 'Fixed by user'), ('completed', 'Completed by warehouse'), ('cancelled', 'Cancelled by warehouse')], default='cart', max_length=20),
        ),
    ]
