# Generated by Django 3.2.4 on 2021-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_name',
            field=models.CharField(default='Store1', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_num',
            field=models.IntegerField(default=1),
        ),
    ]
