# Generated by Django 3.2.4 on 2021-08-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('serial_num', models.CharField(max_length=10, unique=True)),
                ('author_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pubdate', models.DateField()),
                ('status', models.CharField(choices=[('new', 'New book'), ('ordered', 'Ordered book'), ('deleted', 'Deleted book')], default='new', max_length=20)),
                ('order_num', models.IntegerField(default=None)),
                ('update_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('order_date', models.DateField()),
                ('store_num', models.IntegerField()),
                ('store_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_mail', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('basket', 'User basket'), ('fixed', 'Fixed by user'), ('completed', 'Completed by warehouse'), ('cancelled', 'Cancelled by warehouse')], default='fixed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('author_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.order')),
            ],
        ),
    ]
