# Generated by Django 3.2.4 on 2021-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_auto_20210829_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
