# Generated by Django 3.2.4 on 2021-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_alter_book_order_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='OrderLine',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'User cart'), ('fixed', 'Fixed by user'), ('completed', 'Completed by warehouse'), ('cancelled', 'Cancelled by warehouse')], default='fixed', max_length=20),
        ),
    ]
